### ISSUE TITLE
Missing call of VA_START

### ISSUE THREAD

**Issue by tbeu** [weiss/c99-snprintf#2]
As reported by https://github.com/modelica/ModelicaStandardLibrary/issues/2626, is
```c
VA_START(ap, format);
```
missing before the call of VA_COPY in rpl_vasprintf?

https://github.com/weiss/c99-snprintf/blob/27b59ac13b47414000e83f05a246008425c22bb7/snprintf.c#L1492-L1494

**Comment by weiss** [comment]
No, `ap` is handed over by the `vasprintf(3)` caller, so it can't be (re)initialized within the `rpl_vasprintf()` function.  This must be done by the caller.

See, e.g., the [EXAMPLES section][1] in the BSD man page.

[1]: http://man.openbsd.org/vasprintf#EXAMPLES
